### ISSUE TITLE
Missing top bar

### ISSUE THREAD

**Issue by regnamd** [Black4Blade/Pixelvision2#24]
Newest steam client update results in missing navigation bar when viewing any page but library.
![image](https://user-images.githubusercontent.com/124204984/216152673-50e8b84f-e637-415a-a94d-387b748de575.png)

**Comment by Black4Blade** [comment]
Are you sure you got the latest update? I was thinking we had delt with that all ready
It seems to work by me, so just want to make sure before I try to fix it

**Comment by regnamd** [comment]
I'm pretty sure I have the latest version downloaded, that is the one from this repository. To double check I deleted the one in my files and redownloaded the release and the issue still persists.

**Comment by regnamd** [comment]
Didnt mean to close this, new to posting on github.

**Comment by regnamd** [comment]
![image](https://user-images.githubusercontent.com/124204984/216173692-24de9a99-bc41-4d1f-8acb-a5f4d3537c0d.png)
Turns out reinstalling actually broke my library page completely.

**Comment by Black4Blade** [comment]
oww... ok that is really odd... will need to check on that
wait... your big picture is in the wrong space
something is really off there

**Comment by Black4Blade** [comment]
I am not sure mate.. Others seem to say there ok
I think something may be off with your installation there.. can you try to make a new folder for it and put a clean version of the new version from here:
https://github.com/somini/Pixelvision2/archive/master.zip

and see if it works.

**Comment by regnamd** [comment]
This version of the skin seemed to do the trick.  Not sure what the issue was since I had downloaded directly from this repository early today, but everything works now, sorry for being a bother.

**Comment by Black4Blade** [comment]
Not a bother at all mate
Glad its fixed :)

For next time anyway, the place to download is here:
https://github.com/somini/Pixelvision2

As that is where stable versions should be for the time being
